{{ define "header" }}
{{- $tags := tags -}}
{{- $inject := inject -}}
{{- if $tags -}}
//go:build{{ range $tags }} {{ . }}{{ end }}

{{ end -}}
{{- if first -}}
// Package {{ pkg }} contains generated code for schema '{{ schema }}'.
{{ end -}}
package {{ pkg }}

// Code generated by dbtpl (pgx). DO NOT EDIT.

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
{{ range imports }}
	{{ with .Alias }}{{ . }} {{ end }}{{ .Pkg }}
{{ end }}
)

{{- if $inject }}
{{ $inject }}
{{- end }}
{{ end }}
